"""empty message

Revision ID: 4f1d906d45e5
Revises: e8bb4674b10c
Create Date: 2022-04-20 11:43:35.076450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f1d906d45e5'
down_revision = 'e8bb4674b10c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advert_model', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'advert_model', 'user_model', ['owner_id'], ['id'])
    op.drop_column('advert_model', 'owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advert_model', sa.Column('owner', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'advert_model', type_='foreignkey')
    op.drop_column('advert_model', 'owner_id')
    # ### end Alembic commands ###
